### ISSUE TITLE
Incompatible with latest version of urwid.

### ISSUE THREAD

**Issue by airfield20** [taypo/redial#57]
**Describe the bug**
Running redial now produces an error on a fresh install: Module not found error. urwid.tests is not found. Redial seems to be compatible with urwid version 2.1.2

**To Reproduce**
1. Pip install redial
2. Run redial 

**Expected behavior**
Redial app should start

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04

**Additional context**
Current workaround is to uninstall urwid and install version 2.1.2

pip uninstall urwid
pip install urwid==2.1.2

**Comment by Qadosch** [comment]
fixing this error with an pipx installation:
```
pipx list
```
gives you path to localy installed venvs, in my case `/home/oleg/.local/pipx/venvs`

then you go
```
source /home/oleg/.local/pipx/venvs/redial/bin/activate
python -m pip install urwid==2.1.2
```

**Comment by fatihbaltaci** [comment]
This issue was fixed in the latest [version of redial](https://github.com/taypo/redial/releases/tag/0.9).
